src/Entity/Equipo.php
<?php

namespace App\Entity;

use App\Repository\EquipoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EquipoRepository::class)
 */
class Equipo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $nombre;

    /**
     * @ORM\Column(type="integer")
     */
    private $liga;

    /**
     * @ORM\Column(type="integer")
     */
    private $tam_plantilla;

    /**
     * @ORM\Column(type="float")
     */
    private $presupuesto;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_fundacion;

    /**
     * @ORM\OneToMany(targetEntity=Jugador::class, mappedBy="equipo")
     */
    private $jugador;

    public function __construct()
    {
        $this->jugador = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getLiga(): ?int
    {
        return $this->liga;
    }

    public function setLiga(int $liga): self
    {
        $this->liga = $liga;

        return $this;
    }

    public function getTamPlantilla(): ?int
    {
        return $this->tam_plantilla;
    }

    public function setTamPlantilla(int $tam_plantilla): self
    {
        $this->tam_plantilla = $tam_plantilla;

        return $this;
    }

    public function getPresupuesto(): ?float
    {
        return $this->presupuesto;
    }

    public function setPresupuesto(float $presupuesto): self
    {
        $this->presupuesto = $presupuesto;

        return $this;
    }

    public function getFechaFundacion(): ?\DateTimeInterface
    {
        return $this->fecha_fundacion;
    }

    public function setFechaFundacion(\DateTimeInterface $fecha_fundacion): self
    {
        $this->fecha_fundacion = $fecha_fundacion;

        return $this;
    }

    /**
     * @return Collection<int, Jugador>
     */
    public function getJugador(): Collection
    {
        return $this->jugador;
    }

    public function addJugador(Jugador $jugador): self
    {
        if (!$this->jugador->contains($jugador)) {
            $this->jugador[] = $jugador;
            $jugador->setEquipo($this);
        }

        return $this;
    }

    public function removeJugador(Jugador $jugador): self
    {
        if ($this->jugador->removeElement($jugador)) {
            // set the owning side to null (unless already changed)
            if ($jugador->getEquipo() === $this) {
                $jugador->setEquipo(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->nombre;
    }
}

src/Entity/Jugador.php
<?php

namespace App\Entity;

use App\Repository\JugadorRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=JugadorRepository::class)
 */
class Jugador
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $nombre;

    /**
     * @ORM\Column(type="integer")
     */
    private $posicion;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_nacimiento;

    /**
     * @ORM\Column(type="float")
     */
    private $salario;

    /**
     * @ORM\ManyToOne(targetEntity=Equipo::class, inversedBy="jugador")
     */
    private $equipo;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getPosicion(): ?int
    {
        return $this->posicion;
    }

    public function setPosicion(int $posicion): self
    {
        $this->posicion = $posicion;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fecha_nacimiento;
    }

    public function setFechaNacimiento(\DateTimeInterface $fecha_nacimiento): self
    {
        $this->fecha_nacimiento = $fecha_nacimiento;

        return $this;
    }

    public function getSalario(): ?float
    {
        return $this->salario;
    }

    public function setSalario(float $salario): self
    {
        $this->salario = $salario;

        return $this;
    }

    public function getEquipo(): ?Equipo
    {
        return $this->equipo;
    }

    public function setEquipo(?Equipo $equipo): self
    {
        $this->equipo = $equipo;

        return $this;
    }

    public function __toString()
    {
        return $this->nombre;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Form/EquipoType.php
<?php

namespace App\Form;

use App\Entity\Equipo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EquipoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('liga')
            ->add('tam_plantilla')
            ->add('presupuesto')
            ->add('fecha_fundacion')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Equipo::class,
        ]);
    }
}

src/Controller/EquipoController.php
<?php

namespace App\Controller;

use App\Entity\Equipo;
use App\Form\EquipoType;
use App\Repository\EquipoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/equipo")
 */
class EquipoController extends AbstractController
{
    /**
     * @Route("/", name="app_equipo_index", methods={"GET"})
     */
    public function index(EquipoRepository $equipoRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        return $this->render('equipo/index.html.twig', [
            'equipos' => $equipoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_equipo_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EquipoRepository $equipoRepository): Response
    {
        $equipo = new Equipo();
        $form = $this->createForm(EquipoType::class, $equipo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $equipoRepository->add($equipo);
            return $this->redirectToRoute('app_equipo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('equipo/new.html.twig', [
            'equipo' => $equipo,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_equipo_show", methods={"GET"})
     */
    public function show(Equipo $equipo): Response
    {
        return $this->render('equipo/show.html.twig', [
            'equipo' => $equipo,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_equipo_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Equipo $equipo, EquipoRepository $equipoRepository): Response
    {
        $form = $this->createForm(EquipoType::class, $equipo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $equipoRepository->add($equipo);
            return $this->redirectToRoute('app_equipo_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('equipo/edit.html.twig', [
            'equipo' => $equipo,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_equipo_delete", methods={"POST"})
     */
    public function delete(Request $request, Equipo $equipo, EquipoRepository $equipoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$equipo->getId(), $request->request->get('_token'))) {
            $equipoRepository->remove($equipo);
        }

        return $this->redirectToRoute('app_equipo_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/{id}/jugadores", methods={"GET", "POST"}, name="app_equipo_jugadores")
     */
    public function listajugadores($id)
    {
        $em = $this->getDoctrine()->getManager();
        $equipo = $em->getRepository(Equipo::class)->find($id);

        return $this->render('equipo/jugadores.html.twig', ['equipo' => $equipo]);
    }
}

templates/equipo/edit.html.twig
{% extends 'base.html.twig' %}

        {% block stylesheets %}
            <style>
                body{
                    background-image: url("https://t4.ftcdn.net/jpg/04/21/56/51/360_F_421565174_o2Qihq7OyT9bs3jEe34A1RgaHR1Cc1iG.jpg");
                }
                #titulo{
                    color: white;
                    text-align: center;
                }

                table{
                    text-align: center;
                }
                #card1{
                    width: 50%;
                    height: 50%;
                    margin: auto auto;
                    margin-top: 5%;
                    background: #8a8a8a;
                }
                #CorreoRegistrado{
                    color: white;
                    text-align: center;
                }
            </style>
        {% endblock %}

{% block title %}Edit Equipo{% endblock %}

{% block body %}
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
            <div>
                <h3 class="float-md-start mb-0" id="titulo">Editar Equipo</h3>
                <nav class="nav nav-masthead justify-content-center float-md-end">
                    <a class="nav-link " aria-current="page" href="/">Home</a>
                    <a class="nav-link active" href="/jugador">Jugadores</a>
                    <a class="nav-link" href="/equipo">Equipos</a>
                    <a class="nav-link" href="/Contact.html">Contacto</a>
                </nav>
            </div>
            <div class="mb-3" id="CorreoRegistrado">
                Bienvenido {{ app.user.username }}, <a href="{{ path('app_logout') }}">Cerrar Sesion</a>
            </div>
        </header>
        <br>
        <h3 class="float-md-start mb-0" id="titulo">Equipo: {{ equipo.nombre }}</h3>
        <div class="card" id="card1">
            <div class="card-body">
                {{ include('equipo/_form.html.twig', {'button_label': 'Update'}) }}

                <a href="{{ path('app_equipo_index') }}">back to list</a>

                {{ include('equipo/_delete_form.html.twig') }}
            </div>
        </div>
    </div>


{% endblock %}

templates/equipo/index.html.twig
{% extends 'base.html.twig' %}

        {% block stylesheets %}
            <style>
                body{
                    background-image: url("https://t4.ftcdn.net/jpg/04/21/56/51/360_F_421565174_o2Qihq7OyT9bs3jEe34A1RgaHR1Cc1iG.jpg");
                }
                #titulo{
                    color: white;
                }

                table{
                    text-align: center;
                }
                .bd-placeholder-img {
                    font-size: 1.125rem;
                    text-anchor: middle;
                    -webkit-user-select: none;
                    -moz-user-select: none;
                    user-select: none;
                }

                @media (min-width: 768px) {
                    .bd-placeholder-img-lg {

                        font-size: 3.5rem;
                    }
                }
                #card1{
                    width: 50%;
                    height: 50%;
                    margin: auto auto;
                    margin-top: 5%;
                    background: #8a8a8a;
                }
                #CorreoRegistrado{
                    color: white;
                    text-align: center;
                }

                #btnaddequipo{
                    text-align: center;
                }

                @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');

                .container__background-triangle{
                    max-width: 1200px;
                    height: 600px;
                    position: fixed;
                    top: 50%;
                    left: 50%;
                    transform: translate(-50%, -50%);
                    margin-top: 8%;
                }

                .triangle{
                    width: 300px;
                    height: 300px;
                    background: red;
                    position: absolute;
                }

                .triangle1{
                    width: 250px;
                    height: 250px;
                    background: linear-gradient(to left, orange, #1e67c7);
                    top: 100px;
                    right: 400px;
                    animation: t1 8s ease infinite;
                }

                .triangle2{
                    width: 200px;
                    height: 200px;
                    background: linear-gradient(to left,#1e67c7 ,#5be1c9);
                    top: -150px;
                    animation: t2 9s ease infinite;
                }

                .triangle3{
                    width: 300px;
                    height: 300px;
                    background: linear-gradient(to left, #1b8fc5, red);
                    left: 370px;
                    animation: t3 7s ease infinite;
                }

                @keyframes t1 {
                    0%{
                        transform: rotate(45deg) translateY(0px);
                    }
                    50%{
                        transform: rotate(45deg) translateY(20px);
                    }
                    100%{
                        transform: rotate(45deg) translateY(0px);
                    }
                }

                @keyframes t2 {
                    0%{
                        transform: rotate(65deg) translateY(0px);
                    }
                    50%{
                        transform: rotate(65deg) translateY(20px);
                    }
                    100%{
                        transform: rotate(65deg) translateY(0px);
                    }
                }

                @keyframes t3 {
                    0%{
                        transform: rotate(45deg) translateY(0px);
                    }
                    50%{
                        transform: rotate(45deg) translateY(20px);
                    }
                    100%{
                        transform: rotate(45deg) translateY(0px);
                    }
                }

                #titulo{
                    text-align: center;
                }
                #imglogo{
                    width: 70%;
                    height: 70%;
                    padding-left: 20%;
                }
            </style>
        {% endblock %}

        {% block javascripts %}
            <script>
                $(document).ready( function () {
                    $('#myTable').DataTable({
                        "language": {
                            "url": "//cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish.json"
                        }
                    });
                } );
            </script>
        {% endblock %}

{% block title %}Lista Equipos{% endblock %}

{% block body %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0" id="titulo">SYMFONY</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link " aria-current="page" href="/">Home</a>
                <a class="nav-link active" href="/jugador">Jugadores</a>
                <a class="nav-link" href="/equipo">Equipos</a>
                <a class="nav-link" href="/Contact.html">Contacto</a>
            </nav>
        </div>
        <div class="mb-3" id="CorreoRegistrado">
            Bienvenido {{ app.user.username }}, <a href="{{ path('app_logout') }}">Cerrar Sesion</a>
        </div>
    </header>
    <br>
    <div class="container__background-triangle">
        <div class="triangle triangle1"></div>
        <div class="triangle triangle2"></div>
        <div class="triangle triangle3"></div>
    </div>
    <h3 class="float-md-start mb-0" id="titulo">Lista Equipos</h3>
    <div class="card" id="card1">
        <div class="card-body">
    <table id="myTable" class="table table-dark table-striped table-bordereddt-responsive nowrap" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Liga</th>
                <th>Tam_plantilla</th>
                <th>Presupuesto</th>
                <th>Fecha_fundacion</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for equipo in equipos %}
            <tr>
                <td>{{ equipo.id }}</td>
                <td>{{ equipo.nombre }}</td>
                <td>{{ equipo.liga }}</td>
                <td>{{ equipo.tamPlantilla }}</td>
                <td>{{ equipo.presupuesto }}</td>
                <td>{{ equipo.fechaFundacion ? equipo.fechaFundacion|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_equipo_show', {'id': equipo.id}) }}"><i class="bi bi-eye-fill"></i></a>
                    <a href="{{ path('app_equipo_edit', {'id': equipo.id}) }}"><i class="bi bi-pencil-square"></i></a>
                    <a href="{{ path('app_equipo_jugadores', {'id': equipo.id}) }}"><i class="bi bi-people"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
            <div class="card-footer" id="btnaddequipo">
                <a id="btnAñadir" type="button" class="btn btn-secondary" href="{{ path('app_equipo_new') }}">Crear aquipo</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/equipo/jugadores.html.twig
{% extends 'base.html.twig' %}

        {% block stylesheets %}
            <style>
                body{
                    background-image: url("https://t4.ftcdn.net/jpg/04/21/56/51/360_F_421565174_o2Qihq7OyT9bs3jEe34A1RgaHR1Cc1iG.jpg");
                }
                #titulo{
                    color: white;
                    text-align: center;
                }

                table{
                    text-align: center;
                }
                #card1{
                    width: 50%;
                    height: 50%;
                    margin: auto auto;
                    margin-top: 5%;
                    background: #8a8a8a;
                }
                #CorreoRegistrado{
                    color: white;
                    text-align: center;
                }
                #btnvolver{
                    text-align: center;
                }
            </style>
        {% endblock %}

    {% block javascripts %}
        <script>
            $(document).ready( function () {
                $('#myTable').DataTable({
                    "language": {
                        "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
                    }
                });
            } );
        </script>
    {% endblock %}

{% block body %}
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
            <div>
                <h3 class="float-md-start mb-0" id="titulo">Lista jugadores</h3>
                <nav class="nav nav-masthead justify-content-center float-md-end">
                    <a class="nav-link " aria-current="page" href="/">Home</a>
                    <a class="nav-link active" href="/jugador">Jugadores</a>
                    <a class="nav-link" href="/equipo">Equipos</a>
                    <a class="nav-link" href="/Contact.html">Contacto</a>
                </nav>
            </div>
            <div class="mb-3" id="CorreoRegistrado">
                Bienvenido {{ app.user.username }}, <a href="{{ path('app_logout') }}">Cerrar Sesion</a>
            </div>
        </header>
    </div>
        <br>
    <h3 id="titulo">Jugadores del {{ equipo.nombre }}</h3>
        <div class="card" id="card1">
            <div class="card-body">
                <table id="myTable" class="table table-dark table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Posicion</th>
                        <th>Fecha_nacimiento</th>
                        <th>Salario</th>
                        <th>Equipo</th>
                        <th>actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for jugador in equipo.jugador %}
                        <tr>
                            <td>{{ jugador.id }}</td>
                            <td>{{ jugador.nombre }}</td>
                            <td>{{ jugador.posicion }}</td>
                            <td>{{ jugador.fechaNacimiento ? jugador.fechaNacimiento|date('Y-m-d') : '' }}</td>
                            <td>{{ jugador.salario }}</td>
                            <td>{{ jugador.equipo }}</td>
                            <td>
                                <a href="{{ path('app_jugador_show', {'id': jugador.id}) }}"><i class="bi bi-eye-fill"></i></a>
                                <a href="{{ path('app_jugador_edit', {'id': jugador.id}) }}"><i class="bi bi-pencil-square"></i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="6">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="card-footer" id="btnvolver">
                    <a type="button" class="btn btn-primary" href="{{ path('app_equipo_index') }}">Volver</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/equipo/new.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <style>
        body{
            background-image: url("https://t4.ftcdn.net/jpg/04/21/56/51/360_F_421565174_o2Qihq7OyT9bs3jEe34A1RgaHR1Cc1iG.jpg ");
        }
        #titulo{
            color: white;
        }
        #card1{
            width: 50%;
            height: 50%;
            margin: auto auto;
            margin-top: 10%;
            background: #8a8a8a;
        }
    </style>
{% endblock %}

{% block title %}New Equipo{% endblock %}

{% block body %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0" id="titulo">Crear Equipo</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link " aria-current="page" href="/">Home</a>
                <a class="nav-link active" href="/jugador">Jugadores</a>
                <a class="nav-link" href="/equipo">Equipos</a>
                <a class="nav-link" href="/Contact.html">Contacto</a>
            </nav>
        </div>
    </header>

    <div class="card" id="card1">
        {{ include('equipo/_form.html.twig') }}

        <a href="{{ path('app_equipo_index') }}">back to list</a>
    </div>
{% endblock %}

templates/equipo/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <style>
        body{
            background-image: url("https://t4.ftcdn.net/jpg/04/21/56/51/360_F_421565174_o2Qihq7OyT9bs3jEe34A1RgaHR1Cc1iG.jpg");
        }
        #titulo{
            color: white;
            text-align: center;
        }

        table{
            text-align: center;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
        #card1{
            width: 50%;
            height: 50%;
            margin: auto auto;
            margin-top: 10%;
            background: #8a8a8a;
        }
        #card2{
            width: auto;
            height: auto;
            margin: auto auto;
            margin-top: -20%;
            background: #8a8a8a;
        }
        #CorreoRegistrado{
            color: white;
            text-align: center;
        }
    </style>
{% endblock %}

{% block title %}Equipo{% endblock %}

{% block body %}
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0" id="titulo">SYMFONY</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link " aria-current="page" href="/">Home</a>
                <a class="nav-link active" href="/jugador">Jugadores</a>
                <a class="nav-link" href="/equipo">Equipos</a>
                <a class="nav-link" href="/Contact.html">Contacto</a>
            </nav>
        </div>
        <div class="mb-3" id="CorreoRegistrado">
            Bienvenido {{ app.user.username }}, <a href="{{ path('app_logout') }}">Cerrar Sesion</a>
        </div>
    </header>
        <br>
        <h3 class="float-md-start mb-0" id="titulo">Club: {{ equipo.nombre }}</h3>
    <div class="card" id="card1">
        <div class="card-body">
    <table class="table table-dark table-striped table-bordered">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ equipo.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ equipo.nombre }}</td>
            </tr>
            <tr>
                <th>Liga</th>
                <td>{{ equipo.liga }}</td>
            </tr>
            <tr>
                <th>Tam_plantilla</th>
                <td>{{ equipo.tamPlantilla }}</td>
            </tr>
            <tr>
                <th>Presupuesto</th>
                <td>{{ equipo.presupuesto }}</td>
            </tr>
            <tr>
                <th>Fecha_fundacion</th>
                <td>{{ equipo.fechaFundacion ? equipo.fechaFundacion|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>
    </div>
        </div>
    </div>
    </div>
    </div>

    <div class="btn-group-vertical" id="card2">
        <a type="button" class="btn btn-primary" href="{{ path('app_equipo_index') }}">Volver</a>

        <a type="button" class="btn btn-info" href="{{ path('app_equipo_edit', {'id': equipo.id}) }}">Editar</a>

        <a type="button">{{ include('equipo/_delete_form.html.twig') }}</a>
    </div>
{% endblock %}